# $ docker-compose up -d

version: "3.7"

services: 
    basket.grpc.db:
        container_name: basket-grpc-db
        image: redis
        ports:
            - 6379:6379
        restart: always

    basket.grpc.api:
        container_name: basket-grpc-api
        build:
            context: ../
            dockerfile: BasketAPI.Grpc/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTPS_PORT=5001
            - ASPNETCORE_URLS=https://+:5001
            - ASPNETCORE_Kestrel__Certificates__Default__Password=localhost
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
            - "CacheSettings:ConnectionString=basket.grpc.db:6379"
        depends_on:
            - basket.grpc.db
        ports: 
            - 5001:5001
        volumes:
            - ~/.aspnet/https:/https:ro
