# $ docker-compose up -d

version: "3.7"

services: 
    basket.db:
        container_name: basket-db
        image: redis
        ports:
            - 6379:6379
        restart: always

    basket.api:
        container_name: basket-api
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CacheSettings:ConnectionString=basket.db:6379"
        depends_on:
            - basket.db
        ports: 
            - 3000:80
